CREATE TABLE IF NOT EXISTS item_types(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	item_type_name VARCHAR (50)
);

CREATE TABLE IF NOT EXISTS items(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	item_name VARCHAR (50),
	item_type_id INT REFERENCES item_types(id)
);

CREATE TABLE IF NOT EXISTS cities(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	city_name VARCHAR (50)
);

CREATE TABLE IF NOT EXISTS customers(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	customer_name VARCHAR (50),
	birthday DATE,
	city_id INT REFERENCES cities(id)
);

CREATE TABLE IF NOT EXISTS orders(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	customer_id INT REFERENCES customers(id)
);

CREATE TABLE IF NOT EXISTS order_items(
	PRIMARY KEY(order_id,item_id),
	order_id INT REFERENCES orders(id),
	item_id INT REFERENCES items(id)
);